-- Team data
INSERT INTO team VALUES (108, 'ana', 'Los Angeles Angels', 'Angels');
INSERT INTO team VALUES (109, 'ari', 'Arizona Diamondbacks', 'Diamondbacks');
INSERT INTO team VALUES (110, 'bal', 'Baltimore Orioles', 'Orioles');
INSERT INTO team VALUES (111, 'bos', 'Boston Red Sox', 'Red Sox');
INSERT INTO team VALUES (112, 'chn', 'Chicago Cubs', 'Cubs');
INSERT INTO team VALUES (113, 'cin', 'Cincinnati Reds', 'Reds');
INSERT INTO team VALUES (114, 'cle', 'Cleveland Indians', 'Indians');
INSERT INTO team VALUES (115, 'col', 'Colorado Rockies', 'Colorado');
INSERT INTO team VALUES (116, 'det', 'Detroit Tigers', 'Tigers');
INSERT INTO team VALUES (117, 'hou', 'Houston Astros', 'Astros');
INSERT INTO team VALUES (118, 'kca', 'Kansas City Royals', 'Royals');
INSERT INTO team VALUES (119, 'lan', 'Los Angeles Dodgers', 'Dodgers');
INSERT INTO team VALUES (120, 'was', 'Washington Nationals', 'Nationals');
INSERT INTO team VALUES (121, 'nyn', 'New York Mets', 'Mets');
INSERT INTO team VALUES (133, 'oak', 'Oakland Athletics', 'Athletics');
INSERT INTO team VALUES (134, 'pit', 'Pittsburgh Pirates', 'Pirates');
INSERT INTO team VALUES (135, 'sdn', 'San Diego Padres', 'Padres');
INSERT INTO team VALUES (136, 'sea', 'Seattle Mariners', 'Mariners');
INSERT INTO team VALUES (137, 'sfn', 'San Francisco Giants', 'Giants');
INSERT INTO team VALUES (138, 'sln', 'St. Louis Cardinals', 'Cardinals');
INSERT INTO team VALUES (139, 'tba', 'Tamba Bay Rays', 'Rays');
INSERT INTO team VALUES (140, 'tex', 'Texas Rangers', 'Rangers');
INSERT INTO team VALUES (141, 'tor', 'Toronto Blue Jays', 'Blue Jays');
INSERT INTO team VALUES (142, 'min', 'Minnesota Twins', 'Twins');
INSERT INTO team VALUES (143, 'phi', 'Philadelphia Phillies', 'Phillies');
INSERT INTO team VALUES (144, 'atl', 'Atlanta Braves', 'Braves');
INSERT INTO team VALUES (145, 'cha', 'Chicago White Sox', 'White Sox');
INSERT INTO team VALUES (146, 'flo', 'Florida Marlins', 'Marlins');
INSERT INTO team VALUES (147, 'phi', 'New York Yankees', 'Yankees');
INSERT INTO team VALUES (158, 'mil', 'Milwaukee Brewers', 'Brewers');
