-- Park data
INSERT INTO park VALUES (1, 'Angel Stadium of Anaheim', 'Anaheim, CA');
INSERT INTO park VALUES (2, 'Oriole Park at Camden Yards', 'Baltimore, MD');
INSERT INTO park VALUES (3, 'Fenway Park', 'Boston, MA');
INSERT INTO park VALUES (4, 'U.S. Cellular Field', 'Chicago, IL');
INSERT INTO park VALUES (5, 'Progressive Field', 'Cleveland, OH');
INSERT INTO park VALUES (7, 'Kauffman Stadium', 'Kansas City, MO');
INSERT INTO park VALUES (8, 'Hubert H. Humphrey Metrodome', 'Minneapolis, MN');
INSERT INTO park VALUES (10, 'Oakland Coliseum', 'Oakland, CA');
INSERT INTO park VALUES (12, 'Tropicana Field', 'St. Petersburg, FL');
INSERT INTO park VALUES (13, 'Rangers Ballpark in Arlington', 'Arlington, TX');
INSERT INTO park VALUES (14, 'Rogers Centre', 'Toronto, ON');
INSERT INTO park VALUES (15, 'Chase Field', 'Phoenix, AZ');
INSERT INTO park VALUES (16, 'Turner Field', 'Atlanta, GA');
INSERT INTO park VALUES (17, 'Wrigley Field', 'Chicago, CA');
INSERT INTO park VALUES (19, 'Coors Field', 'Denver, CO');
INSERT INTO park VALUES (20, 'Dolphin Stadium', 'Miami, FL');
INSERT INTO park VALUES (22, 'Dodger Stadium', 'Los Angeles, CA');
INSERT INTO park VALUES (31, 'PNC Park', 'Pittsburgh, PA');
INSERT INTO park VALUES (32, 'Miller Park', 'Milwaukee, WI');
INSERT INTO park VALUES (680, 'Safeco Field', 'Seattle, WA');
INSERT INTO park VALUES (2392, 'Minute Maid Park', 'Houston, TX');
INSERT INTO park VALUES (2394, 'Comerica Park', 'Detroit, MI');
INSERT INTO park VALUES (2395, 'AT&T Park', 'San Francisco, CA');
INSERT INTO park VALUES (2602, 'Great American Ball Park', 'Cincinnati, OH');
INSERT INTO park VALUES (2680, 'PETCO Park', 'San Diego, CA');
INSERT INTO park VALUES (2681, 'Citizens Bank Park', 'Philadelphia, PA');
INSERT INTO park VALUES (2889, 'Busch Stadium III', 'St. Louis, MO');
INSERT INTO park VALUES (3289, 'Citi Field', 'Flushing, NY');
INSERT INTO park VALUES (3309, 'Nationals Park', 'Washington, DC');
INSERT INTO park VALUES (3313, 'Yankee Stadium II', 'Bronx, NY');
